name: Build Docker Image and Create AWS Instance

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


jobs:
  build_and_create_instance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/wlcompetency:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/wlcompetency:${{ github.sha }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Change to your desired Terraform version

      - name: Execute Terraform
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Check Running Containers
        run: docker ps




