name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/wlcompetency:${{ github.sha }} .
       
      # - name: Log in to Docker Hub
      #   run: docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }}
      - name: Run Docker Container
        run: |
          docker run -d -p 8080:80 ${{ env.DOCKER_USERNAME }}/wlcompetency:${{ github.sha }}
      
      - name: Check Running Containers
        run: docker ps
      # - name: Push Docker Image
      #   run: |
      #     docker push ${{ env.DOCKER_USERNAME }}/wlcompetency:${{ github.sha }}


